server { # 本地Trojan发送到域名的流量
    listen 127.0.0.1:80 default_server;

    server_name dd72899.tk;

    location / {
        proxy_pass https://www.ietf.org;
    }

}

server { # 本地Trojan发送到ip的流量重定向到域名
    listen 127.0.0.1:80;

    server_name 108.166.194.82;

    return 301 https://dd72899.tk:933$request_uri;
}

server { # 外部请求的80伪装为站点
    listen 0.0.0.0:80;
    listen [::]:80;

    server_name _;

	root /var/www/html;
	index index.html;

	location / {
		try_files $uri $uri/ =404;
	}

    location /.well-known/acme-challenge {
       root /var/www/acme-challenge;
    }
}
