server { # 本地Trojan发送到域名的流量
    listen 127.0.0.1:80 default_server;

    server_name mydomain.me;

    location / {
        proxy_pass https://www.ietf.org;
    }

}

server { # 本地Trojan发送到ip的流量重定向到域名
    listen 127.0.0.1:80;

    server_name 104.xxx.xxx.xx;

    return 301 https://mydomain.me:933$request_uri;
}

server { # 外部请求的80伪装为站点
    listen 0.0.0.0:80;
    listen [::]:80;

    server_name _;

	root /var/www/html;
	index index.html;
	#location / {
	#	proxy_pass http://127.0.0.1:12580;
	#}

    location /.well-known/acme-challenge {
       root /var/www/acme-challenge;
    }
}
