server { # internal file
    listen 127.0.0.1:80;
    server_name 127.0.0.1;
    root /var/www/html;
    location = /sub {
        index sub;
        add_header Content-Type text/plain;
    }
}

server { # accept all traffic from port 80. 
    listen 0.0.0.0:80;
    listen [::]:80;

    server_name _;

	root /var/www/html;
	index index.html;
	#location / {
	#	proxy_pass http://127.0.0.1:12580;
	#}

    location /.well-known/acme-challenge {
       root /var/www/acme-challenge;
    }

    location = /sub {
        return 404;
    }
}